package com.stockmarket.model.enums;

public enum ScreenerIndicator {
    // Fundamentals
    PE, EPS, EPS_GROWTH, REVENUE_GROWTH, MARKET_CAP, DIVIDEND_YIELD,
    DEBT_TO_EQUITY, CURRENT_RATIO, ROA, GROSS_MARGIN, ASSET_TURNOVER,
    RETAINED_EARNINGS, EBIT, WORKING_CAPITAL, TOTAL_ASSETS, TOTAL_LIABILITIES,
    OPERATING_CASH_FLOW, SHARES_OUTSTANDING,
    // Technicals
    RSI_14, MACD_VALUE, MACD_SIGNAL, MACD_HISTOGRAM,
    SMA_20, SMA_50, SMA_200,
    HIGH_52W, LOW_52W, CURRENT_PRICE, VOLUME, AVG_VOLUME
}
